# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sPC7ctG4xsMBSgOifvkak6QMez7LfvWW
"""

from google.colab import files
data_to_load=files.upload()

import pandas as pd
import csv
import plotly.express as px
df=pd.read_csv("data1.csv")
mean=df.groupby(["student_id","level"],as_index=False)["attempt"].mean()
fig=px.scatter(mean,x="student_id",y="level",size="attempt",color="attempt")
fig.show()